language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - PHP_CURRENT='5.6'

before_script:
  - composer selfupdate

script:
  - make phpunit
  - if [ $(phpenv version-name) = $PHP_CURRENT ]; then make test-upload; fi
  - if [ $(phpenv version-name) = $PHP_CURRENT ]; then make phpcs phpmd bugfree; fi

after_script:
  - make clean

matrix:
  fast_finish: true
