language: php
 
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - phpenv version-name
  - composer selfupdate
  - composer install -vvv --dev

script: 
  - make test

after_success:
  - make test-upload

notifications:
  webhooks:
    urls:
      - http://satisio.us/repositories/buildhook/
    on_success: always
    on_failure: always
    on_start: true
